### ISSUE TITLE
Keep history

### ISSUE THREAD

**Issue by tasn** [JeffHoogland/moksha#1]
Hey,

While I'm not 100% about the decision to fork (though I get it, and agree with most of your thoughts). I think you should have kept (you can still do it, rewrite history) the git history.
1. It's very useful when debugging/tracing issues.
2. Pay some respect to the 20 years of hard work you're basing this fork on.
3. Why not?

I can offer my help if you need it.

**Comment by JeffHoogland** [comment]
Really good idea.

**Comment by tasn** [comment]
Fixed. Pushing now.
