### ISSUE TITLE
Clipboard module has no visible icon

### ISSUE THREAD

**Issue by texstar** [JeffHoogland/moksha#101]
Moksha 0.3.1 does not appear to show a visible icon for the clipboard when added to the panel.

**Comment by texstar** [comment]
I added a new profile and by gawd the little booger showed up on my taskbar!

**Comment by thewaiter** [comment]
Hello

We need more info. Do you mean Moksha Clipboard module or other clipboard manager like Parcellite for example? I tried removing and re-adding Moksha clipboard module from and back to panel and I see no issue here. Screenshot or screen video would be great to see to be attached.

Stefan

**Comment by texstar** [comment]
I was trying to use the La Capitaine Icons but it kept locking up the Startup Applications Menu when I noticed the Moksha Clipboard wasn't on the the taskbar. However it appears it was there but the same color as the taskbar which made it appear invisible. I switched to the Adwaita Icons and could then see the Moksha Clipboard on the taskbar.

**Comment by rbtylee** [comment]
La Capitaine Icons work fine in Moksha. Oddly enough I was checking it out a few days ago. Moreover, that icon set does indeed have a Clipboard icon:

[Screenshot](https://i.imgur.com/vXQ4RzK.jpg)

The clipboard icon is the one on the right end of the bottom shelf.

If the Application menu was locking up and some icons like Clipboard were not showing you had some other problem. I suspect a corrupted file in your configuration or hmm who knows?

**Comment by texstar** [comment]
La Capitaine Icons locks up Moksha when I try to access the Startup Applications menu from the settings menu and can you see the icon in the attached picture? It is there but almost the same color as the taskbar. I can see it with the lights off. This is a brand new install of the Moksha 0.3.1 desktop on PCLinuxOS.  Like you said who knows man. LOL

![clipboard](https://user-images.githubusercontent.com/6324233/65839093-b425e200-e2cf-11e9-8ec5-cae9a3af78a4.png)

**Comment by rbtylee** [comment]
Strange. My install of that icon set was from git hub, how was yours installed? If not from git update to the git version. On the menu issue  there was an efl bug in efl > 1.20 or was that efl 1.21. How as efl installed and what version? If from downloads at enlightenment try the git version. I would recommend the efl version branch 1.21.1 or efl 1,22.4. The aforementioned bug has been fixed in those branches. If none of that works take a look at stderr messages. I assume ya know how, if not let us know.
