### ISSUE TITLE
Autohide shelf causes shelf content to disappear too early.

### ISSUE THREAD

**Issue by riban-bw** [JeffHoogland/moksha#117]
- Configure shelf to autohide.
- Enter shelf to show it.
- Leave shelf.
- Expected behaviour: Shelf hides (with slide animation) after configured duration.
- Actual behaviour: Shelf content disappears immediately then shelf hides (with slide animation) after configured duration.

Systray does not suffer this issue, remaining visible but all other widgets disappear: Battery, Clipboard, Cock, iBar, Pager, Mixer, Start, System, Tasks.

Observed in Bodhi Linux 5.1 Legacy and 6.0 pre-alpha 64-bit.

**Comment by rbtylee** [comment]
Thanks for reporting. Interesting observation, I seldom using shelves that auto-hide.

However, this is not really a moksha bug. The only theme provided by moksha is the default theme (that is what it is called in the Settings). If you switch to the default theme, the shelf acts as expected when autohiding is enabled. At least it does here.

But it does appear the MokshaArcGreen theme has this issue. So it is a theme issue and we will take a look at it, ASAP. Perhaps we also need to test Bodhi Linux's remaining themes for this bug.

**Comment by thewaiter** [comment]
FIxed

https://github.com/thewaiter/enlightenment-arc-theme/commit/fca85a5c078bf06cfa06e988b85a3e0497df9163

Stefan
