### ISSUE TITLE
Clicking on menu closes menu

### ISSUE THREAD

**Issue by riban-bw** [JeffHoogland/moksha#118]
- Open menu by clicking on desktop or menu widget on shelf
- Click on a menu category, e.g. Applications
- Expected behaviour: Submenu opens
- Actual behaviour: Menu closes / disappears

This has particularly impact when using a touchscreen making it difficult / unintuitive to navigate menus with the touchscreen. A workaround is to click and drag to highlight a submenu menu.

**Comment by thewaiter** [comment]
I can make that behavior possible but it has one glitch. The "Settings" and "System" items in the main menu are clickable and opens dialogs. I do not know about possibility to check if callback function exist to each menu item...

Stefan

**Comment by thewaiter** [comment]
Solved
