### ISSUE TITLE
Chrome can no longer drag tabs from one browser window to another

### ISSUE THREAD

**Issue by JeffHoogland** [JeffHoogland/moksha#14]
This was working on E17.6, so I assume this is another issue with the border backports. When I have two chrome windows open I should be able to drag tabs between them. This is no longer possible with the current Moksha git code.

**Comment by JeffHoogland** [comment]
It is likely worth noting that I am pretty sure this is also broken in E19 - so it would make sense that if the backports came form there.

**Comment by drammelt** [comment]
Cannot reproduce this issue with google-chrome-43.0.2357.81. Tabs drag back and forward between windows, both across desktops and on the same desktop. It is unlikely that E itself would affect this behavior it is more likely a dbus issue? I have not looked into what signalling chrome uses.

**Comment by JeffHoogland** [comment]
I'll play with it some more. Maybe something with Ecomorph is causing the issue. Will try disabling it.

**Comment by Elw3** [comment]
To isolate the problem play around with.
Settings>windows>window focus>Focus>new window focus 
I can reproduce the problem only when this is set to all windows. 
Pretty sure it used to work even with this on. 
Another note: Chromium ignores the window raise setting, means the window gets raised by a click even if that is disabled, i feel there is a connection.

**Comment by drammelt** [comment]
I use the setting New Window Focus>All Windows, has been almost 2 weeks now and not reproduced this issue once. The tab I am tying in was dragged from one chrome with window to another. I have tried all of these settings.
How do you disable raising of a window without click? There are override settings that force always raising on click but afaik nothing to disabled it completely?

**Comment by JeffHoogland** [comment]
I can confirm that these settings under window focus -> https://www.enlightenment.org/ss/e-55819fbeb66355.00140463.jpg

Cause drag between windows to not work. Setting new window focus to anything else allows it to work as expected here. 

Chrome has always ignored stacking settings for some reason under E. The settings for that are here -> http://www.enlightenment.org/ss/e-5581a0a9ea3e40.82909099.jpg but Chrome always raises on any click regardless of what is set here.

**Comment by Elw3** [comment]
No, not always.
At least i can tell right now it worked in bodhi 1.x times. 
Whether the chrome or E version makes the difference is an other question. 
Mixing old/new versions might give us a hint to see if it is something new in E that causes it or an old bug in E that chrome triggered with something new.

**Comment by drammelt** [comment]
Using my existing ~/.e folder I can reproduce this using settings given by Jeff.

However using a fresh ~/.e folder does not exhibit this behaviour. Yay binary config?

**Comment by kaihu** [comment]
Decompile both config files with eet and use diff to compare. Probably a stale setting somewhere that is being picked up by e.

**Comment by JeffHoogland** [comment]
This was resolved awhile ago. Check the commit log.
