### ISSUE TITLE
[E2Moksha] Replace "Enlightenment" string with "Moksha [Desktop]"

### ISSUE THREAD

**Issue by avDuma** [JeffHoogland/moksha#15]
Probably there's a lot of places to edit, but I've found on src/bin/e_actions.c , line 2150 the config dialog
```c
 e_dialog_text_set(exit_dialog, _("Are you sure you want to exit Enlightenment?"));
```
Maybe we have to replace Enlightenment with Moksha, isn't it?
And, of course, on all the translations file.
For example, on po/it.po on line 90
```po
#: src/bin/e_actions.c:2124
msgid "Are you sure you want to exit Enlightenment?"
msgstr "Siete sicuri di voler uscire da Enlightement?"
```

**Comment by drammelt** [comment]
Fixed. Replaced all translation occurance, and all source String type occurance. I have left alone the X-Enlightenment types as I am unsure what else they might affect and they are not displayed in anycase.
https://github.com/JeffHoogland/moksha/commit/fa31dd515999364150b21691b3483be340e0849e
https://github.com/JeffHoogland/moksha/commit/fd88a8c391ad29cf60b68fc2ba2af7fe1d5014bc
