### ISSUE TITLE
[EFM] efm_navigation pathbar can't be scrolled with arrow button on default theme

### ISSUE THREAD

**Issue by avDuma** [JeffHoogland/moksha#16]
Hi, me again that open tickets. :)

While I'm theming on Moksha (from Bodhi Repos) I've found that issue on EFM and default dark theme (not theme related) when the pathbar goes too long for its window and arrow buttons appear to scroll its content.

User can scroll the content with mouse wheel, but clicking the arrow gets no effect.
From a theme side, there's two program that gets launched when user click the arrow button: the changing of pixmap state and the signal_emit "e,action,prev" (or "e,action,next").
Pixmap state is correctly changed(arrow goes blue), but the scroll doesn't appear.

I suppose it is not a big dealt, but it's something that doesn't work.
![](http://www.enlightenment.org/ss/e-5572eae65c4235.88209897.png)

**Comment by drammelt** [comment]
Confirmed.

To clarify it is clicking the arrow buttons that has no effect.

**Comment by JeffHoogland** [comment]
Who would be heart broken if we simply stripped EFM out of Moksha? It needs a lot of work and I really do not want to invest time into it. I think simply integrating the places module would be the best option then people can use whatever file manager they think is best.

For folks wanting an EFL / Elm based file manager this one looks promising -> https://github.com/marcelhollerbach/jesus

**Comment by avDuma** [comment]
I agree, but maybe we can try to keep the icons on desktop, what do you think?

**Comment by JeffHoogland** [comment]
That seems like something users expect / want. I'll dig into the source and see how easy it will be to simply open the files when clicked with xdg-open

**Comment by avDuma** [comment]
It will be the coolest thing.
We have to keep the desktop part of EFM and all the "open with..." settings (even if also that part has some annoying bugs)

**Comment by JeffHoogland** [comment]
EFM is being removed from Moksha which makes this no longer a valid issue.
