### ISSUE TITLE
Keep credit when due!

### ISSUE THREAD

**Issue by tasn** [JeffHoogland/moksha#17]
Guys, again, regarding #1, what's wrong with you?!?!
You can't just steal credit, when you backport, maintain authorship!!! (Why not just cherry-pick the commit? Easier anyway).

One example of many similar commits:
https://github.com/JeffHoogland/moksha/commit/14da9fbf68e29c6c102f735f189634131508c5e2

**Comment by JeffHoogland** [comment]
We maintain a backport log here -> https://github.com/JeffHoogland/moksha/blob/master/BACKPORTS

But will look into maintaining the correct author on the commits in the future.

**Comment by drammelt** [comment]
I dont understand sorry. I have linked back to the original commit. What more should be done, I am in no way intending to steal credit...

**Comment by tasn** [comment]
Thank you guys for your prompt replies. As explained to Jeff on IRC, Git supports attributing credit correctly in a clean manner. Git has two concepts, an author (who wrote the patch), and a committer (who brought this patch here). You are the committer, not the author.

It's very simple to use "git cherry-pick" or a combination of "git format-patch" and "git am" (google either solution and see what works best for you) to backport fixes for a different project. It's even easier than whatever method you've probably been using.

Please read about these concepts and let me know if you need any help.

**Comment by drammelt** [comment]
Well in about 30% of the patches my method has been re-writing them from scratch since the API does not exist in E17, or the methods/variables have not been implemented yet. Another 30% or so fail to apply at all and the locations in the code do not exist yet and require rejiggery to get them in the correct spot doing what theyre were intended for. The other 40% or so are just the 1 liner OOPs bugs.

Using those methods 40% of the backports would work using your method (This is why I think they were never officially backported to E17, too hard basket). None of those methods are really suitable unless the patch applies cleanly, otherwise I think they would just cause more work.

In anycase this is what seems to be required.

git commit --amend --author="User Name <user@abc.com>"

I will use this from now on, thanks for the heads up!

**Comment by tasn** [comment]
There's some misunderstanding here, let me clarify based on the types you described.

Patches you end up rewriting: you should probably be the author, but you should refer to the original commit in the patch.
Patches that fail to apply and need some jigging: you are not the author, you should retain the original author, and add a mention that there were conflicts (git am and git cherry-pick both do this automatically, and they also let you resolve conflicts).
Patches that just apply: again, git cherry-pick or git am as described before.

There are various reasons to why we don't backport some patches. Some were done after the EOL of E17, so we didn't bother, some were changes that are too intrusive to backport to a stable version and some we just forgot. They are suitable for cases 2 and 3 as described above, possibly not for case 1, but that should be your starting point. They also include the original commit message (which is important for identifying the patch in upstream). Please read more about git cherry-pick and git am, they are wonderful tools. Git cherry-pick was specifically created for the task you are doing, backporting changes.

git commit --amend will let you amend the last commit. Alternatively, you can just add the --author part to when you do the commit itself, no need to first commit and then amend. However, I'd still recommend going down the git cherry-pick path, this tool was created just for that. Trust me it works, I use it all the time.

I consider this issue close for now (as it seems you understand the issue for the future). It's similar to #1 (as previously mentioned), it's a matter of playing nicely with the project and people who's work you use.

**Comment by drammelt** [comment]
Thanks for the verbose reply. Makes alot more sense now.

**Comment by tasn** [comment]
Pleasure.

**Comment by tasn** [comment]
Seriously guys? What the fuck?
14da9fbf68e29c6c102f735f189634131508c5e2

This is so disrespectful, I thought we covered this already...

**Comment by drammelt** [comment]
No disrespect, but did you even look at the date on that commit? Not really sure where this is coming from?

**Comment by tasn** [comment]
Haha, my bad, I was just sent this as a recent example of this, I believed the guy who sent me this, and didn't even look.

There are other examples though: 644a303c0ad3080109d773645deed456a08bc885

Sorry for my rash blow out, but please watch out for that.
