### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by hugok79** [JeffHoogland/moksha#172]
This sentence/string and others below start with a space. Is it on purpose or is it a typo?

https://github.com/JeffHoogland/moksha/blob/58a5d2f3c390c2b9a89c3b49d8b4c024495e9ebb/po/moksha.pot#L5754

If I not mistaken, there are about 51 setences/strings that starts with a space...

**Comment by thewaiter** [comment]
Hi Hugo. Good point. My little typo, yes. THX :) I will fix it

Stefan

**Comment by thewaiter** [comment]
Spaces in key binginding viewer solved. There are still some I need to have with space:
" Show the Desktop:". It is because it is alligned to left side.

**Comment by thewaiter** [comment]
OK Hugo, po files updated. Check pt please. Maybe br also.

**Comment by hugok79** [comment]
Ok, I have already checked **pt.**
 Now only 31 sentences star with a space. those start with a space on purpose, right?

Below is an image with **Poedit** 

![Captura de ecrã 2022-09-15 223656](https://user-images.githubusercontent.com/16929048/190513959-5f8c760d-e5c7-44e2-a3c8-288cd6ebc7af.jpg)

I could check the **pt_BR** but I prefer a native Brazilian to do it.

**Comment by thewaiter** [comment]
Yes, those others with space are on purpose.

**Comment by hugok79** [comment]
Ok, thank you.
