### ISSUE TITLE
Moksha should provide an xsessions-file

### ISSUE THREAD

**Issue by tfla** [JeffHoogland/moksha#19]
To brand Moksha in a Display Manager like LightDM an xsessions .desktop file is required (preferrably /usr/share/xsessions/moksha.desktop). As far as I can see, this is not the case either in Bodhi 3.0 with Moksha installed from apt-get or from source. I don't really know if the file should be provided by the package manager or the installation scripts, but here's how one might look:

```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Moksha
Comment=Log in using Moksha (Version x.y.z)
Icon=/usr/share/enlightenment/data/images/enlightenment.png
TryExec=/usr/bin/enlightenment_start
Exec=/usr/bin/enlightenment_start
```

(the Icon, TryExec, and Exec values being dependent on where Moksha was installed to, the example above assumes the current default.)

**Comment by JeffHoogland** [comment]
This file had always existed.
