### ISSUE TITLE
Edit color_classes "Border Frame" and "Border Frame Active" style

### ISSUE THREAD

**Issue by avDuma** [JeffHoogland/moksha#2]
Like on E19, I report a super-simple change to do on Moksha:

I've noticed that the color_classes "Border Frame" and "Border Frame Active" should be displayed as Space, not like Text, so it is necessary to edit on /src/modules/conf_theme/e_int_config_color_classes.c .

Here the phab task for details: https://phab.enlightenment.org/T1637

**Comment by drammelt** [comment]
This is fixed. 
https://github.com/drammelt/moksha/commit/86143a45f8bafa8013546d9195af595b11e8cb8e
