### ISSUE TITLE
If a Moksha menu contains more entries than could be displayed by a vertical resolution, it shows nothing.

### ISSUE THREAD

**Issue by astroboynext** [JeffHoogland/moksha#22]
If a Moksha menu contains more entries than could be displayed by a vertical resolution, it shows nothing.

Way to reproduce the bug:
1. Set a computer to a low vertical setting, say, 800x600 or 1024x600.
2. Install a package that installs a lot of entries in a menu category. For example, a good option could be 'kdegames', which installs a lot of apps for the "Games" menu category.
3. As kdegames package installs a lot of programs, their menu entries cannot be shown all at once in a 600 vertical resolution (not even in my machine, at 1440x900). As a result, the "Games" menu does not show anything at all, as if Games were an empty category with no programs installed.

The same issue described with kdegames as an example, could happen in any category menu in which the user could install more programs than the vertical resolution available in his/her computer and not be able to display all the programs in a category at once.

If the test computer has the possibility to be set to a higher vertical resolution (say, 1600x1200), restart Moksha, and all the menu entries in the Games category are going to be visible. Of course, this workaround is not possible in every computer, and in others would be straining to the eye the need to have high resolutions merely to be able to see all the items in a menu category.

This seems to be a variant of the bug described for E17 in http://forums.bodhilinux.com/index.php?/topic/8271-not-all-programs-are-displayed-in-bodhi-menu/?hl=%2Bmenu+%2Bitems#entry69762

**Comment by thewaiter** [comment]
Solved for main menu in this commit
https://github.com/JeffHoogland/moksha/commit/e0e0f8dede8a476f08a85ac085ad1c6dfabc85f9

I will leave this issue opened because it does not work for the Clipboard history menu.

**Comment by thewaiter** [comment]
The commit https://github.com/JeffHoogland/moksha/commit/72888a7a948240b928c4da715973a6b1cbc11b40 is solving this. Only submenus were able to scroll in full range. Main menu was not. Clipboard menu used that main menu for showing history. Now it works as expected although we are thinking of using the e_widget_list component in the future.
For now I am closing this issue...
