### ISSUE TITLE
iBar Not Launching Apps

### ISSUE THREAD

**Issue by tenplus1** [JeffHoogland/moksha#226]
The latest Moksha update in Bodhi 7.0 to 0.4.1-1 seems to have broken iBar from launching apps after being clicked on.  I can still launch from the menu and right-clicking desktop.

**Comment by thewaiter** [comment]
Yep, my fault. iBar config did not update to my new structure item related to Plank style control. Middle click to launch app, left click to activate all borders. I will fix it soon. Thx

**Comment by tenplus1** [comment]
Thanks, running update now and it works fine :)
