### ISSUE TITLE
File Manager launcher on the bottom title bar produces Error

### ISSUE THREAD

**Issue by CarlGluck** [JeffHoogland/moksha#23]
When I click the File Manager icon on the bottom gadget bar it produces an error without opening the File Manger. The File Manager works properly from the desktop left click application starter.

BTW: very nice system. Good job!

**Comment by JeffHoogland** [comment]
What file manager are you trying to launch?

**Comment by CarlGluck** [comment]
Enlightenment File Manager

**Comment by JeffHoogland** [comment]
The Enlightenment file manager is not supported in Moksha and does not have any launchers present by default.

It will be fully stripped out of the code base in a future release.

**Comment by CarlGluck** [comment]
Interestingly, I don't see the file manager in the iBar, just Midori

**Comment by CarlGluck** [comment]
Thank you!
