### ISSUE TITLE
Errors building and installing Moksha from source on Xubuntu 15.04

### ISSUE THREAD

**Issue by fusion809** [JeffHoogland/moksha#24]
Hi, 

I have attempted to build and install Moksha 0.1.0 from the source code contained in this GitHub repo and while the build appears to have succeeded (i.e., I received no error message from running `./configure && make && sudo make install`) I cannot run `/usr/local/bin/enlightenment_start` and hence I cannot start a Moksha session. For further details please see [this question](http://askubuntu.com/q/662479/93125) on Ask Ubuntu. Naturally you may wonder why I don't just install Bodhi and use it instead of trying to install Moksha on Xubuntu, well I am running Xubuntu on a virtual machine and I have installed several programs on it (including SageMath from source code which took several hours) and I don't want to start from scratch on Bodhi. 

Thanks for your time,
Brenton

**Comment by JeffHoogland** [comment]
Have you provided the bodhi profile data that is not currently included in Moksha as mentioned in the [0.1.0 release notes](https://github.com/JeffHoogland/moksha/releases/tag/0.1.0)? Without it the startup wizard won't have setup files for your desktop to use and will likely result in something like a black screen.

Also - we include debian packaging data files in the moksha repo - so you should be able to simply run:

    dpkg-buildpackage -b -rfakeroot

With the proper dependencies installed and it should produce a .deb package for you.

Alternatively when you install in the future make sure to call **./autogen.sh** instead of calling configure directly.

**Comment by fusion809** [comment]
I hadn't tried this, but I just tried the .deb package building line but it gave the message: 

```sh
dpkg-buildpackage: source package moksha
dpkg-buildpackage: source version 20150712-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by root <Jeff Hoogland <jeffhoogland@linux.com>>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build moksha
dpkg-source: warning: unknown information field 'Depends' in input data in general section of control info file
dpkg-checkbuilddeps: Unmet build dependencies: efl edbus
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

I may be a real noob at programming but I did get the meaning of this message which was I needed to install efl and edbus but simply running `sagi efl edbus` fails to do the job (`sagi` is the name of a function I set up in my `~/.bashrc` file it's full form is `sudo apt-get install -y $@`). I widened the scope of the command with the wildcard operator (*) to `sagi efl*` and it essentially gave me that it conflicted with other packages on my system (probably because I dragged my net too wide), while `sagi edbus*` gave: 

```sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libedbus1' for regex 'edbus*'
Note, selecting 'libedbus-dev' for regex 'edbus*'
Note, selecting 'python-edbus' for regex 'edbus*'
libedbus-dev is already the newest version.
libedbus1 is already the newest version.
python-edbus is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

could you please help me out in determining the solution to this dependency issue? As for `./autogen.sh` I am running it now, but I was wondering whether these missing dependencies may be part of the reason I keep failing to run Moksha.

**Comment by JeffHoogland** [comment]
Ahhh - Bodhi packages have different naming conventions than Ubuntu does. libedbus-dev should cover edbus and efl headers you have will cover efl. You will need to edit the control file for this still though.

**Comment by fusion809** [comment]
efl headers are efl-dbg and efl-doc (see for example http://packages.ubuntu.com/search?keywords=efl&searchon=names) right?

**Comment by JeffHoogland** [comment]
I think so? Honestly not sure. I always build those from source.

**Comment by fusion809** [comment]
I built the deb package successfully (although signing it failed) and installed it, but I still can't seem to start moksha. I also re-ran `./autogen.sh && make && sudo make install`, after the efl headers were installed and it failed to load too.

**Comment by fusion809** [comment]
I went into tty1, Moksha installed by the autogen procedure is installed at `/usr/local/bin/enlightenment_start` while Moksha installed by the debian package is at `/usr/bin/enlightenment_start`. I attempted to start both in tty1 and they both gave errors saying that Ecore_X couldn't be started.

**Comment by JeffHoogland** [comment]
Did you see my comment about profile data?

**Comment by fusion809** [comment]
I did but my technical knowledge is limited so I skimmed passed it hoping that the methods for installing Moksha ya provided would bypass it.

**Comment by fusion809** [comment]
So I just have to download https://github.com/JeffHoogland/bodhi3packages/blob/master/bodhi-profile-moksha/DEBIAN/control and use it to replace the control file in the debian subdirectory of this repo? Is that all I need to do?

**Comment by JeffHoogland** [comment]
You need to copy the profile data (the folder with the .cfg files) to the directory I specified.

**Comment by fusion809** [comment]
is there any way I can download that directory in one go? i.e., I don't want to have to download each of the .cfg files myself, manually.

**Comment by fusion809** [comment]
Copied `*.cfg` files to `~/Programs/moksha/config/default` (`~/Programs` is where I cloned this git repo) and re-ran `dpkg-buildpackage -b -rfakeroot`. Is that what I was meant to do?

**Comment by JeffHoogland** [comment]
Please follow the directions in the release notes. I am closing this issue because it is not valid.
