### ISSUE TITLE
compliation error onFedora22

### ISSUE THREAD

**Issue by Baggypants** [JeffHoogland/moksha#25]
CCLD     enlightenment
enlightenment-e_int_menus.o: In function `_e_int_menus_clients_title_abbrv':
/home/baggypants/rpmbuild/BUILD/moksha-0.1.0/src/bin/e_int_menus.c:1460: undefined reference to `eina_unicode_utf8_next_get'
collect2: error: ld returned 1 exit status

May be an unmet dependency. Not sure.

**Comment by JeffHoogland** [comment]
What version of EFL / Eina do you have?

**Comment by Baggypants** [comment]
ah, It's because I'm an idiot this bug https://bugzilla.redhat.com/show_bug.cgi?id=1256696 means I haven't got efl-devel installed. I'll sort that out and get back to you.
