### ISSUE TITLE
Can't drag windows between workspaces

### ISSUE THREAD

**Issue by dwrl** [JeffHoogland/moksha#251]
Hello,

I can't enable window dragging. I know it is possible, since I did manage to enable this on e17 in the past.

**What I did:**
In the dialog 'Virtual Desktop Settings' is a checkbox 'Flip when dragging objects to the screen edge'.
I checked the box, and in the dialog 'Window Geometry', unchecked 'Snap windows to screen edges (translated from German, might be a bit fuzzy)'.

**What I expect:**
Dragging a window over the screen edge moves the viewport to the corresponding workspace, with the window now situated at that workspace.

**What happens:**
The viewport is not changed, and the window remains situated on the current workspace.

**My System:**
Debian 12, Moksha installed using the script found here: https://github.com/BodhiDev/Distros/blob/main/Debian/bookworm.install.sh

Maybe I'm just missing something here, is there something else I need to configure for this? *shrug*

**Comment by thewaiter** [comment]
Thank you for reporting. Yes, I added a snap against screen edge to the Moksha code. If you disable that feature, it should help. Let me check and if possible I will fix it

**Comment by thewaiter** [comment]
OK, I tested the feature on BL7, BL6, BL5 and BL3. I was not able to see this feature in action. Maybe I am also missing something. I will check E25 when I get home. Stefan

**Comment by thewaiter** [comment]
OK, all you need is disable snap feature, enable flip feat in virtual settings and add edge bindings for edges. Be aware of virtual screens direction (left/right vs up/down).

**Comment by dwrl** [comment]
Thank you for looking into this. So far I got it working, with a caveat:
I can't find a way to not have the edge binding trigger when not dragging a window, i.e. the workspace is switched even if I just place my mouse cursor at the screen edge now. This is very bad for playing DooM, I must constrain ;)

Just to surmise, I had assumed from a functional point of view that  'Flip when dragging objects to the screen edge' would enable exactly that, while the edge binding independently allows me to configure edge binding, regardless of that. One fires by dragging, the other by pointing / clicking.

Right now it seems as if  'Flip when dragging objects to the screen edge' just enables the activation of edge bindings while dragging windows.

--

I looked at it in Enlightenment, seems they added a checkbox to the edge binding dialog to allow firing it only on dragging. I guess the labelling of 'Flip when dragging objects to the screen edge' was a bit misleading from the start on this one then.

**Comment by thewaiter** [comment]
OK. I tried to make an E port to Moksha. Success after a few days. I will commit soon after some testings :)
Stefan

**Comment by dwrl** [comment]
Thank you, I just tried it out, works like a charm ;)

For reference to those socialized with that oldschool behaviour:

- Config Dialog 'Virtual Desktop Settings'
- -> 'Flip when dragging objects to the screen edge'
- Config Dialog 'Edge Bindings':
- -> Add edge binding for workspace switching, mind the direction.
Done.

**Comment by thewaiter** [comment]
Great. Now I should rethink how to use both snapping and flipping features together
