### ISSUE TITLE
Moksha background errors on Sabayon Linux

### ISSUE THREAD

**Issue by fusion809** [JeffHoogland/moksha#27]
Hi,

I've been trying to build Moksha on my Sabayon machine. I have installed all dependencies with Entropy and Portage and then I managed to install Moksha with `./configure && make && sudo make install`. The problem is the following:
* Firstly, I can't seem to change the desktop background. I just have a black background ([here](http://i.imgur.com/r396IPR.png)'s a screenshot). 
* Secondly, as soon as I log out Moksha seems to forget any changes I made (like new shelves I added, gadgets I added to said shelves, modules I've laoded, *etc.*)
* Thirdly, whenever I try to change the theme, Moksha crashes and gives me this error message
![1](http://imgur.com/w33fuLi.png)

Thanks for your time,
Brenton

**Comment by JeffHoogland** [comment]
Did you have existing profile data from a newer E release in your ~/.e directory? Did you manually provide the profile data for Moksha like the 0.1.0 release notes say you need to do?

**Comment by fusion809** [comment]
Oh hallelujah it is now working. Although just a note, for me I need the .cfg files in /usr/local/share/enlightenment/data/config/default. Oh and btw what theme does Moksha use, by default, on Bodhi Linux? I've noticed that my desktop doesn't quite look like Moksha does on Bodhi Linux.

**Comment by JeffHoogland** [comment]
Radiance -> https://github.com/JeffHoogland/MokshaRadiance

**Comment by fusion809** [comment]
Thanks, I'm closing.
