### ISSUE TITLE
Randr Leaves Primary Screen Blank after Secondary is Removed

### ISSUE THREAD

**Issue by JeffHoogland** [JeffHoogland/moksha#28]
To produce:

Attach a second screen to a laptop and disable the laptop's screen while leaving the secondary screen on.

If you shut the system down in this setup the next time you turn the system on the laptop's primary disable will still be blank even if the secondary screen is now removed.

**Comment by kaihu** [comment]
You can remove randr setup by commenting out https://github.com/JeffHoogland/moksha/blob/master/src/bin/e_main.c#L568-L575

**Comment by JeffHoogland** [comment]
Resolved via commit https://github.com/JeffHoogland/moksha/commit/a6bfc9c487b0c12931196c0d7c0c02e069100255
