### ISSUE TITLE
move enlightment libs to moksha 

### ISSUE THREAD

**Issue by necrose99** [JeffHoogland/moksha#29]
evas mokshavas
ecore mokshacore
mokshacore-mvas 

etc thus if up-stream causes breakage you can port over some features etc. , but as the libs are more Moksha specific mate did. freezing libs as moksa libs would keep it viable for some time , avoiding any up-stream SNAFU's , code can be back-ported or just sync/renamed , extended , features added onto , etc that would make it unique , as well if you use multiple window managers ,
ie i still at times roll up good YE OLDEN , windowmaker , IE chroot's and doing multiple compile jobs 
but still  some window managers offer a good experiance , other like gnome3 i don't know what b@#& they been smoking at times lol 

** Long Term Packaging support** this would reduce breakages , and with rolling distro's like Gentoo 
Sabayon , Arch etc make it far eassier to package from sources , libs having differing names from e17 wont **collided** if user/s  installs say E19 20 etc down the line. though you can have prefixes etc like /opt/bin/moksa/moksa  </smyL> </usr/bin/moksa> etc , if the libs have same name its a recipe for hell.  later down the line. 

however pruning enlightenment artifacts. 
with a few odd commands (Gentoo can spit out rpm's from source emerge jobs, alien > slack,deb etc. )  for now with a few hacks unpacker.eclass allows for debs/rpms/etc to be installed.  however this isn't as kosher . I'm an astute user however not a gentoo-dev. 
 I've learned enough how to make my own overlay/s.

**Comment by JeffHoogland** [comment]
I have zero intention of forking upstream EFL / Elementary. If they cause API breaks with an update that is a bug in EFL and should be reported upstream. The EFL API is supposed to remain backwards compatible until their 2.0 release - and who knows when that will happen.

**Comment by necrose99** [comment]
ok no big'gy for now , I'm just wrapping it via debs into gentoo ,  hopefully I can Rig one of the old  E-17 ebuilds , and Enlightenment eclass > Moksha.eclass , a bit Frankenstein~y  but that''ll  be a while.
but for tinkering will make a 9999 version (LIVE) all that more easier.
