### ISSUE TITLE
Dialog window crop its content if it is bigger than window.

### ISSUE THREAD

**Issue by avDuma** [JeffHoogland/moksha#3]
Dialog window on E17 keeps a fixed size even if the contents are bigger than the window.

An example is the dialog window displayed before kill an application:
![Dialog_normal](http://www.enlightenment.org/ss/e-555323a38debc0.52493876.jpg)

Now I'll set a smaller size and another line will be displayed
![Dialog_small](http://www.enlightenment.org/ss/e-555324250d5257.81659013.jpg)
on the default situation (showed above), the "Siete sicuri di voler uccidere questa finestra?" line (on english: "Are you sure to want to kill that window?" or something similar) is cropped because the dialog window has a fixed size, I suppose.

I've seen this issue, as pictured, with the default theme, so it is not theme-related.

**Comment by JeffHoogland** [comment]
I've never understood why dialog windows can't just have normal window controls. Thoughts?

**Comment by JeffHoogland** [comment]
Dialog windows can be resized normally for awhile now.
