### ISSUE TITLE
Build in Arch Linux

### ISSUE THREAD

**Issue by zenway-js** [JeffHoogland/moksha#32]
Hello.
Anybody have any ideas how to build it in ArchLinux distro ?

**Comment by JeffHoogland** [comment]
Someone recently prepared package builds for compiling on arch -> http://forums.bodhilinux.com/index.php?/topic/13102-how-to-install-moksha-on-arch-linux-and-derivatives/#entry96986

**Comment by Airon90** [comment]
I created a page on Archwiki's wiki: https://wiki.archlinux.org/index.php/Moksha

**Comment by hippytaff** [comment]
Not sure if this is the same as the arch wiki, but anyway...

http://forums.bodhilinux.com/index.php?/topic/13102-how-to-install-moksha-on-arch-linux-and-derivatives/?hl=arch

**Comment by Airon90** [comment]
Already posted by @JeffHoogland 
Moreover, it is linked in the Arch Linux wiki

**Comment by hippytaff** [comment]
Sweet
