### ISSUE TITLE
Opinion about Moksha

### ISSUE THREAD

**Issue by Alexey-T** [JeffHoogland/moksha#43]
Tried Badhi with Moksha 1st time..

1.Terminal is too deeply hidden in menu, hard to find
1b. Terminal not called with CtrlAltT (as i use on Ubuntu)
1c. Why name "Terminology", i must guess that it is terminal..

2.Main prob I cannot install CudaText via deb-file: i run it and installer ok, but Sudo asks a pass, i dont know the pass.
- i entered empty, and app didnt install
- i entered "badhi" - it dont fit
- i cannot find pass in faq...

**Comment by JeffHoogland** [comment]
None of these things are Moksha bugs. If you need help configuring your bodhi system to your liking please open a support request thread on the Bodhi user forums.
