### ISSUE TITLE
Moksha Freeze

### ISSUE THREAD

**Issue by wjwieland** [JeffHoogland/moksha#45]
Issue:
Moksha will freeze the desktop when an application is moved from one monitor to another if the monitors are not the same size.  

Description:
When an application is dragged from one monitor to another of different size, Moksha will enter a state where 

- all application windows are locked in place on the desktop
- keyboard entry is ignored except for within open applications windows
- CPU usage on at least one core is maxed out
- mouse clicks are ignored outside of application windows

Observations:
-The only way found to recover is to reboot the system.
- The speed at which one move the application from one monitor to the other does seem to have an impact. Moving/dragging more slowly sometimes prevents the freeze.
- This issue is believed to be exacerbated by the fact that 'windows raise on focus' settings do not seem to work in Moksha 0.2.1.

Notes on attached files:
- xsession_error has been trimmed to include only the applicable error.

[xrandr_to_report.txt](https://github.com/JeffHoogland/moksha/files/651730/xrandr_to_report.txt)
[lsb_release.txt](https://github.com/JeffHoogland/moksha/files/651762/lsb_release.txt)
[xsession_error_to_report.txt](https://github.com/JeffHoogland/moksha/files/651728/xsession_error_to_report.txt)

**Comment by JeffHoogland** [comment]
Does this happen every time you move a window from one screen to another or sporadically? What is the GPU in the system in question? What drivers are in use with the GPU? What EFL version are you using? What do you mean by "not the same size"? Different resolutions or different physical dimensions?

**Comment by qwertyuser1983** [comment]
Confirmed in my case. 

Switching between full (means many app run) desktops (I run 9) sometimes induces a lock up, I cant click any Bodhi icon nor panel, but my current windows work normally. When I click exit, almost complete freeze; mouse working, so I must induce reboot. :)

**Comment by JeffHoogland** [comment]
Qwerty I don't understand the description of your issue, but it sounds like it is different from the multi screen issue this thread is about (even the result of both is a Moksha freeze). 

Please open a new issue detailing the steps to reproduce you issue on command and include detailed system specs.

**Comment by wjwieland** [comment]
_Does this happen every time you move a window from one screen to another or sporadically?_
   I am usually able to avoid the lock freeze if I move an app window from one monitor to the other very slowly and am careful to ensure that the window extents will stay within the screen extents of the monitor I am moving the app window too.

_What is the GPU in the system in question?_
I have included the output of lshw run with sudo privs below(lshw.txt).  I am not entirely familiar with the hardware as listed, so will hope that this provides you with what you are looking for.  Apparently and Intel GPU with  915 driver as close as I can tell.
[lshw.txt](https://github.com/JeffHoogland/moksha/files/656244/lshw.txt)

_What EFL version are you using?_ 
According to synaptic, the EFL version is: 201610281.18.1bodhi-1

_What do you mean by "not the same size"? Different resolutions or different physical dimensions?_
The monitors are each a different physical size.  Resolution is set @ 1920x1080 on all of them.  I believe the sizes are listed (in mm) in the previously included xrandr_to_report.txt file.  

Please do let me know if there is anything else I can provide that might be helpful.  And thanks so much for getting back to me.  This version of Bodhi is pretty darn nice.  Fast and clean.  I just need it to work with my displays.

**Comment by JeffHoogland** [comment]
So the lock is more likely to occur if you leave the window split between the two screens?

I have an almost identical setup I use once or twice a week and never see a lock up. Also with an Intel graphics card.

Can you please try enabling the Bodhi testing branch and run a system update and see if the lock still occurs with the newer EFL version from there?

**Comment by wjwieland** [comment]
I have enabled the testing branch and done an apt-get distro-upgrade.  This seems to have cleared up the freeze issue for me thus far.  I am going to call this good for now.  There still the issues with the control of windows focus and raise not being slowed down by adjusting the delay, but that is a separate issue to this now I think.  

Thanks for the direction.  I will revisit this issue if this does happen again, but for now it seems to be solved.

**Comment by JeffHoogland** [comment]
Can you see if the work around applied here resolves your issue: http://forums.bodhilinux.com/index.php?/topic/14036-solved-moksha-segfault/?p=102916

**Comment by JeffHoogland** [comment]
This is resolved by using EFL 1.19
