### ISSUE TITLE
Gentoo problem start autogen.sh

### ISSUE THREAD

**Issue by delvin-fil** [JeffHoogland/moksha#49]
> configure: WARNING: EFM requirements : ecore >= 1.7.10 ecore-file >= 1.7.10 ecore-ipc >= 1.7.10 eet >= 1.7.10 efreet >= 1.7.10 edbus >= 1.7.10 eina >= 1.7.10  dbus-1 checking for E_FM... no configure: error: Package requirements (ecore >= 1.7.10 ecore-file >= 1.7.10 ecore-ipc >= 1.7.10 eet >= 1.7.10 efreet >= 1.7.10 edbus >= 1.7.1  0 eina >= 1.7.10  dbus-1  ) were not met:
> 
> No package 'edbus' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> Alternatively, you may set the environment variables E_FM_CFLAGS
> and E_FM_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

What to do?

**Comment by JeffHoogland** [comment]
You need to install the edbus package. Can find the source code for it here: https://download.enlightenment.org/releases/e_dbus-1.7.10.tar.gz

**Comment by delvin-fil** [comment]
Well, thank you, it's gone, but it does this:

> .in'ig.status: error: cannot find input file: `

**Comment by delvin-fil** [comment]
Solved
I did 
`tr -d "\15\32" < configure > configure.new`

**Comment by JeffHoogland** [comment]
What build commands are you running to see that error message?

**Comment by delvin-fil** [comment]
./configure

**Comment by JeffHoogland** [comment]
Please run the autogen.sh as opposed to running the configure script directly.

**Comment by delvin-fil** [comment]
Can't repeat, computer far. Tomorrow will do.
