### ISSUE TITLE
Application icons not showing

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#51]
It seems all the icons under /usr/share/icons directories and possibly some under /home are not being loaded. Is Moksha looking for these at all?

All of the ones under /usr/share/pixmaps are being loaded it seems.

**Comment by JeffHoogland** [comment]
Not being loaded where?

**Comment by srakitnican** [comment]
In menu and titlebars.

Maybe efl-1.19.0 as available from Fedora 25 have to do something with it.
![screenshot from 2017-09-17 17-14-47](https://user-images.githubusercontent.com/13233146/30522190-509664ea-9bcc-11e7-8b38-0b8fe9750929.jpg)

**Comment by JeffHoogland** [comment]
You need to tell Moksha which icon set you want it to use. Application theme settings -> Icons.

**Comment by srakitnican** [comment]
That was it!

Is there a way to set some defaults on a fresh install? Not even neutral themed `/usr/share/icons/hicolor/` and such doesn't get loaded.

**Comment by srakitnican** [comment]
Finally took some time to look into this. The reason why this happens is because predefined `icon_theme` 'Faenza' does not exist by default. https://github.com/JeffHoogland/moksha/blob/0510ff23fc7889a150450efcc115bb0e0681940f/config/bodhi/e.src#L6414

I've set it to 'Enlightenment-X' provided by EFL since that is a requirement for moksha so it will likely be present.

**Comment by JeffHoogland** [comment]
At some point when time permits we should probably have a bodhi default profile and a profile without extras in it as part of the Moksha source.

**Comment by thewaiter** [comment]
This icon issue was solved by Ylee. You need to install moksha-menu package and then select it under menu settings. It also works fine with lxde-menu in the menu settings list.

**Comment by srakitnican** [comment]
Yeah it works if I select something, but that is not the point.

I think it should work with default settings. The default resources should be either included here or should be specified as a dependency.

**Comment by thewaiter** [comment]
Hmm, yes, it should work with default. I am just installing the BL 5.0 RC on one NTB. I will check it
