### ISSUE TITLE
Missing modules on startup (places, clipboard epulse)

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#52]
So by default desktop is giving a warning dialog about missing modules, but these seems to not be installed with the base desktop. Since I had no sound by default, I've packaged epulse from moksha-pulsemixer project, but I can't find where these other modules comes from. Are those necessary at all?

**Comment by JeffHoogland** [comment]
They are optional (you get the option to unload them when the error pops up) you can find the source code for them on my GitHub.

**Comment by thewaiter** [comment]
Almost all extra modules which we maintain are here:
https://github.com/JeffHoogland/moksha-modules-extra
some more are on my git hub (Clipboard, StickyNotes)
https://github.com/thewaiter/

**Comment by thewaiter** [comment]
Maybe a better way is login to Bodhi Linux forum, for perhaps better feedback. 
Can I close this "issue"?
