### ISSUE TITLE
Setuid executables write permission

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#54]
While building the package, I am getting errors like these:
```
extracting debug info from /builddir/build/BUILDROOT/moksha-desktop-0.2.1-1.fc26.x86_64/usr/lib64/enlightenment/modules/cpufreq/linux-gnu-x86_64-0.2.1/freqset
objcopy: unable to copy file '/builddir/build/BUILDROOT/moksha-desktop-0.2.1-1.fc26.x86_64/usr/lib64/enlightenment/modules/cpufreq/linux-gnu-x86_64-0.2.1/freqset'; reason: Permission denied
```
Through the build system files I've noticed that permissions `a=rx,u+xs` are being set, any reason why user is not being given writable permission? e.g. `a=rx,u+wxs`

**Comment by rbtylee** [comment]
Any reason I don't know. It has been this way since we forked e17. Anyway my latest commit b9c7fc2 addresses this issue. I am closing this issue for now but if for any reason this doesn't fix your issue building moksha we will reopen,
