### ISSUE TITLE
Release stuck on 0.2.1

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#61]
I've noticed there was many version bumps over the last year of moksha if I understand correctly, but the latest git tag is stuck on version 0.2.1. What are the plans for that, should we just use commit tarballs to point to a new version or new release is not ready yet?

**Comment by rbtylee** [comment]
While I can't speak for Jeff, he has plans for version 0.3.0. Jeff posted on Bodhi linux forums, Bodhi Team  → Development section only viewable by Team members:

>  I wanna tag a new Moksha release as we head into 5.0.0 for Bodhi as 0.3.0

There is a small todo list in this post so presumably the version change/release will occur when we have implemented and tested everything in this list.

**Comment by JeffHoogland** [comment]
The version bumps you are referring to are likely the Bodhi Linux release version bumps - not Moksha. As Ylee mentioned our goal is to tag a new release before summer

**Comment by thewaiter** [comment]
Can we consider this as bug?

**Comment by rbtylee** [comment]
This is not a bug or an issue as we now have a beta version of moksha 3.0. Just no official release but that should be coming soon as soon I can finish up the last little bit of work in my ever growing todo list. And of course it is stable enough to satisfy us.
