### ISSUE TITLE
data/Backgrounds/Makefile.am: the install-data-local target does not respect the $DESTDIR variable

### ISSUE THREAD

**Issue by TommyD** [JeffHoogland/moksha#66]
As the title says, the install-data-local target ignores the $DESTDIR variable and alsways tries to install into /usr/share/enlightenment/data/backgrounds, which is obviously an issue, if the destination should be somewhere else.

**Comment by TommyD** [comment]
I dont think, a bug in the build system preventing the installation with a proper package manager is just an enhancement.

Anyway, that commit contains the same change i did locally to get the current master branch installed, so that looks fine to me.

**Comment by rbtylee** [comment]
ok closing it then. Thanks.
