### ISSUE TITLE
/usr/bin/mkdir: cannot create directory '/usr/share/enlightenment': Permission denied

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#72]
Testing new `dev` branch commit c380c3055308029ee1a47fbef5e671c47844bf7a, I am getting the following error when building the package.

```
make[2]: Entering directory '/builddir/build/BUILD/moksha/data/backgrounds'
make[3]: Entering directory '/builddir/build/BUILD/moksha/data/backgrounds'
make[3]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /usr/share/enlightenment/data/backgrounds
/usr/bin/mkdir: cannot create directory '/usr/share/enlightenment': Permission denied

```
The build fails on command
`/usr/bin/make install DESTDIR=/builddir/build/BUILDROOT/moksha-desktop-0.3.0-0.1.20180510dev.c380c30.fc25.x86_64`

It looks like `install` target wants to install backgrounds to root, despise DESTDIR is being used.

**Comment by srakitnican** [comment]
What is strange is that I am getting correct directory for stuff previous then `backgrounds`. For example:

```
 /usr/bin/mkdir -p '/builddir/build/BUILDROOT/moksha-desktop-0.3.0-0.1.20180510dev.c380c30.fc25.x86_64/etc/enlightenment'
 /usr/bin/install -c -m 644 sysactions.conf '/builddir/build/BUILDROOT/moksha-desktop-0.3.0-0.1.20180510dev.c380c30.fc25.x86_64/etc/enlightenment'
 ...

 /usr/bin/mkdir -p '/builddir/build/BUILDROOT/moksha-desktop-0.3.0-0.1.20180510dev.c380c30.fc25.x86_64/usr/share/enlightenment/data/icons'
 /usr/bin/install -c -m 644 xterm.png web_browser.png audio_player.png mail_client.png video_player.png text_editor.png image_viewer.png audio_player2.png '/builddir/build/BUILDROOT/moksha-desktop-0.3.0-0.1.20180510dev.c380c30.fc25.x86_64/usr/share/enlightenment/data/icons'
```

**Comment by srakitnican** [comment]
It looks like manually creating the directory is the culprit. This is not necessary as the build system takes care of that automatically. The following patch makes the issue go away:
``` diff
--- data/backgrounds/Makefile.am.orig	2018-05-10 09:00:25.083525742 +0200
+++ data/backgrounds/Makefile.am	2018-05-10 09:00:36.439475163 +0200
@@ -1,6 +1,3 @@
 filesdir = $(datadir)/enlightenment/data/backgrounds
 files_DATA = 
 
-install-data-local:
-	$(MKDIR_P) $(filesdir)
-
```

But then empty `background` dir is not created in destination because there are no files. Not sure if that is a wanted behavior.

**Comment by rbtylee** [comment]
I will look at this this weekend and see if I can duplicate it.

**Comment by srakitnican** [comment]
Didn't see this possibly same issue: https://github.com/JeffHoogland/moksha/issues/66 . Don't know yet of why it doesn't add DESTDIR here, but I think the safest and recommended way is to be explicit [1] [2], for example: `$(MKDIR_P) $(DESTDIR)$(filesdir)`.

[1] https://ftp.gnu.org/old-gnu/Manuals/automake-1.6.1/html_chapter/automake_13.html#SEC67
[2] http://www.astro.gla.ac.uk/~norman/star/ssn78/ssn78.htx/N-a5b2.html
