### ISSUE TITLE
Moksha-dev not compatible with moksha-modules-extra (version in MODULE_ARCH)

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#73]
Seems like `moksha-modules-extra` are no longer compatible with current Moksha master branch since modules use different directories changed by following patch: https://github.com/JeffHoogland/moksha/commit/eb1594e8836afff48f9a04aac63c8128e07b12d6

Extra modules gets installed to `/usr/lib64/enlightenment/modules/<modulename>/linux-gnu-x86_64-0.2.1/`, but current Moksha is looking for module in `/usr/lib64/enlightenment/modules/<modulename>/linux-gnu-x86_64/`.

**Comment by rbtylee** [comment]
They all need a patch to the configure.ac file to remove version number. No one has found the time to do it yet.

**Comment by rbtylee** [comment]
This is not a moksha issue so I am closing it.

**Comment by srakitnican** [comment]
Well, patching `moksha-modules-extra` is not a big problem, the issue is that by doing so modules wont work with current release and vice versa. We either need to do it at the same time as the new release or even better, come up with a compatibility plan, so that modules load from both locations for a while. Not sure what exactly to do for the last one, though. Maybe if not in Moksha code, do it with symbolic links?
linux-gnu-x86_64-0.2.1 -> linux-gnu-x86_64

**Comment by JeffHoogland** [comment]
Patching the extra modules now seems fine if anyone has time to do it. Moksha 0.3.0 should hopefully be tagged as a release soon.

**Comment by srakitnican** [comment]
Created a pull request for the directory rename: https://github.com/JeffHoogland/moksha-modules-extra/pull/31/commits/495598b990a3a5431ee46bb5f62f27a216526a1e

I am trying with the symbolic link idea, while in theory sounded good, in practice does not work very well. Package managers performs poorly directories get replaced by symbolic links and vice versa when package is upgraded.

**Comment by rbtylee** [comment]
Thanks for doing the grunk work for us, merged it :)
