### ISSUE TITLE
epulse allows to increase volume beyond 100%

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#74]
In latest master tree, mixer allows to increase volume beyond 100% with a mouse scroll wheel.

**Comment by thewaiter** [comment]
I am pretty fine with this feature as my Lenovo E31-70 loudspeakers are not very efficient. We had a discussion about this in the Bodhi forums. 
https://forums.bodhilinux.com/index.php?/topic/15112-pulseaudio-security-concerns/&tab=comments#comment-109014

**Comment by srakitnican** [comment]
It says I don't have permissions to view that when I try to open the forum link.

**Comment by thewaiter** [comment]
Oh, sorry. It is under development section :(

**Comment by thewaiter** [comment]
Maybe I will dare to quote Jeff Hoogland:
"Is this really that important? If users want to do something as stupid as crank the volume past 100% to insane levels without listening as they go up, why do we care?"

**Comment by srakitnican** [comment]
> I am pretty fine with this feature as my Lenovo E31-70 loudspeakers are not very efficient

Not sure what you mean by efficient, but if you can't control the volume properly for your machine, I think that it should be fixed at driver level. Are we sure this feature has not a tendency to break hardware?

**Comment by rbtylee** [comment]
Truthfully I am completely unsure and uncomfortable with this "feature". At some point I hope to backport the pulse mixer from e-22 which has some definite improvements plus a number of bug fixes. Among them is [a much saner way of allowing max volume > 100%](https://git.enlightenment.org/core/enlightenment.git/commit/src/modules/mixer/e_mod_main.c?id=1a3086b2c20c79a63f266ebf8dfddc05e9bc193e). This would probably be a rather tedious and time consuming endeavor as e22 now use elm stuff and Moksha or e17 doesn't fully support that.

**Comment by thewaiter** [comment]
Solved:
https://github.com/JeffHoogland/moksha/commit/84f0e03e37d7eccb3aa3e420347f5f1b1f181d88

**Comment by thewaiter** [comment]
https://github.com/JeffHoogland/moksha/commit/84f0e03e37d7eccb3aa3e420347f5f1b1f181d88
