### ISSUE TITLE
Places module missing translations

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha#76]
Seems like po files were omitted on `places` module import. It would be nice to have translation if possible.

**Comment by srakitnican** [comment]
Nevermind, cbd6f36d0446916f42399440752ac79b8144f763 .

**Comment by thewaiter** [comment]
Yea, I was really surprised with your question. I even created a python script to import po files items to moksha core

http://www.enlightenment.org/ss/e-5af7f10714dc39.43663179.png

**Comment by thewaiter** [comment]
Anyway, I don't know your profile, but feel free to participate on moksha locales. It would be great. I assume you can be from Slovenia or Croatia?

**Comment by srakitnican** [comment]
I noticed that files were missing, didn't occur to me that they might be merged :)

I am not using translation because I feel lost when using it. More so, I am not linguist specialist so I would rather not participate :)

**Comment by thewaiter** [comment]
OK then, feel free not to participate :)
