### ISSUE TITLE
Screen Setup Settings Module seems to crash moksha

### ISSUE THREAD

**Issue by TommyD** [JeffHoogland/moksha#84]
If i enable the "Settings - Screen Setup" Module under Settings in "Module Settings" and then go in the Settings -> Screen -> "Screen Setup", it seems like moksha crashes since i see a gdb call in my log. But i dont get any crashdump, any open window from moksha gets closed and moskha gets restarted.

**Comment by JeffHoogland** [comment]
@rbtylee did you add this module back into Moksha? I'm pretty sure this is one of the ones we had removed early on because it was largely buggy and incomplete.

**Comment by rbtylee** [comment]
No I checked on bodhi 4,2 and it is present. Also I went thru the commit history for configure.ac as well as /src/modules/Makefile.am and it is present since before I started this massive update Moksha project. I found the commit where you stripped out e_randr initialization. It is just an artifact that got left in evidently. No big deal.

**Comment by rbtylee** [comment]
For others reading this Jeff Tommy and I talked about this in Discord. The segfault is the result of e_randr_cfg not being initialized as we have removed e_randr stuff from Moksha.

Official story, Jeff:

> It was buggy and feature incomplete.

Relevant parts of a backtrace:

```
#0  0xb3c78137 in _create_data (cfd=0x86f23f8)
    at conf_randr/e_int_config_randr.c:66
#1  0x080a0606 in _e_config_dialog_go (cfd=cfd@entry=0x86f23f8, 
    type=type@entry=E_CONFIG_DIALOG_CFDATA_TYPE_BASIC) at e_config_dialog.c:208
#2  0x080a0858 in e_config_dialog_new (con=0x82c4550, 
    title=0xb3c7d913 "Screen Setup", name=0xb3c7d906 "E", 
    class=0xb3c7d8f2 "screen/screen_setup", 
    icon=0xb3c7d920 "preferences-system-screen-resolution", icon_size=0, 
    view=0x86e57b0, data=0x0) at e_config_dialog.c:87
#3  0xb3c78541 in e_int_config_randr (con=0x82c4550, params=0x0)
    at conf_randr/e_int_config_randr.c:48
#4  0x080a0e8c in e_configure_registry_call (
    path=0x8778be0 "screen/screen_setup", con=0x82c4550, params=0x0)
    at e_configure.c:67
#5  0xb3c6fca0 in _e_configure_item_cb (data=0x8778c40) at conf/e_conf.c:380
```

Checking in gdb and e_randr_cfg is NULL as expected in Function  _create_data, file src/modules/conf_randr/e_int_config_randr.c.

Will fix today most likely.

**Comment by rbtylee** [comment]
My latest commit a1c0a88 addresses this issue. By default this module is not installed. If it is installed by configuration settings then it uses arandr for screen settings. Admittedly it still needs some work as it doesn't inform the user if arandr is not installed, no option for using another program such as xrandr for screen settings, no check in configuration.ac to see if arandr or some other program is installed and so on. I have plans to fix these various 'flaws' in due time but that is low priority. Regardless for the moment it should no longer seg fault here if the screen settings module is installed. For Bodhi users it will not be installed. Anyway I am closing this issue.
