### ISSUE TITLE
On Multiscreen Task Bar Disappears

### ISSUE THREAD

**Issue by bradleyvlr** [JeffHoogland/moksha#88]
I am on Bodhi Linux 5.0.0 obviously with the Moksha desktop.
I am on a Dell Optiplex 7010 with an i5 processor and Intel integrated graphics using mesa driver.
I have two HDMI Monitors, HDMI-1 and HDMI-2

I used 
    xrandr --output HDMI-2 --right-of HDMI-1 //This set my dual monitors

I use three horizontal virtual desktops. But I have tested the issue with many arrangements of virtual desktops, and it is a consistent problem no matter the arrangement.

The taskbar is only on HDMI-1 (which I assume is by design), and whenever I change virtual desktops on HDMI-2, the taskbar disappears from HDMI-1 showing just the desktop background. If I then change virtual desktops on HDMI-1, the taskbar shows back up. I'm not sure if it matters, but I change virtual desktops using key bindings.

That is all of the information that I think is relevant. It is certainly not a huge issue, since it doesn't affect usability.

**Comment by ProhtMeyhet** [comment]
this should be fixed by applying #91
