### ISSUE TITLE
pull enlightenment bugfix "ignore shelves from other screens when changing vdesks"

### ISSUE THREAD

**Issue by ProhtMeyhet** [JeffHoogland/moksha#91]
please pull the bugfix "ignore shelves from other screens when changing vdesks" from enlightenment.

this was [reported to phab.enlightenment.org](https://phab.enlightenment.org/T7422), where it was fixed, but is still an issue in moksha:

> I have a dual screen setup. When changing desktops on one screen the shelf disappears on the other. this behavior is reproducible and very annoying. See the link for a video of the behavior.
> https://youtu.be/LQkydzsKUt0

git id:
Enlightenment/enlightenment@8ad5e3db391df1cc98051d2f94877245a0b2ca27

**Comment by rbtylee** [comment]
Thanks for this I will look at it soon as possible and commit.

**Comment by rbtylee** [comment]
Added to my branch ylee, commit c985838. This branch will be merged into master after fully testing and finishing my current work load there for Moksha 3.1. I am assuming this commit fixes your issue and I am closing it. If not reopen and comment.
