### ISSUE TITLE
If one Virtual Desktop is set on a Multi-Monitor System no Move-To entry in context menu is shown

### ISSUE THREAD

**Issue by vgoehler** [JeffHoogland/moksha#92]
My system consist of three monitors and lately I choose to reduce the virtual desktops to only one.
Then I discovered that the context menu "Move to" Entry had disappeared which is a bit inconvenient.

IMO the condition on line 137 in `src/bin/e_int_border_menu.c` should be expanded to check for not only more than one virtual desktop but additionally for the presence of a multi monitor setup.
This part here:
```
if ((!bd->sticky) && ((bd->zone->desk_x_count > 1) || (bd->zone->desk_y_count > 1)))
     {
        mi = e_menu_item_new(m);
        e_menu_item_label_set(mi, _("Move to"));
```
Something like in `_e_border_menu_cb_sendto_pre` function could work here.
like:
```
 zones = eina_list_count(bd->zone->container->zones);
```
and then check for zones more than one.

**Comment by thewaiter** [comment]
Solved here:
https://github.com/JeffHoogland/moksha/commit/c0f1d3e84927b7d3d0ad9239a39a639226ed48c4
