### ISSUE TITLE
Mouse movement on alt+tab

### ISSUE THREAD

**Issue by drdhaval2785** [JeffHoogland/moksha#95]
I feel that this is more of a bug than a feature.
Whenever I am navigating between let's say a PDF and a txt file, the mouse / cursor lands in the middle of the txt file which makes it difficult to read.

I feel alt+tab is for the people who want to minimize the mouse usage. If my mouse lands on the page and hinders my reading, I am a bit annoyed to move it away from the screen.

**Comment by thewaiter** [comment]
Hello
I think this is more feature than bug. It sounds logical for me. When I want to switch to another window, I would like to have a focus on this window. You want to leave mouse where it is and switch to another window? Weird. Anyway, try to play with windows focus/switcher settings.

Stefan

**Comment by drdhaval2785** [comment]
Hi stephan,
So it is by design that this is so.
Then I have not much of complaint. If tweaking some settings can turn it off for me, I would be happier.

**Comment by JeffHoogland** [comment]
You should be able to adjust this behavior in the "window focus" settings.

**Comment by drdhaval2785** [comment]
I could adjust the behaviour in window focus setting as suggested.
After playing a bit, I realized that it was my mistake to ask for this.
It indeed is a feature.
I withdraw my comment.
