### ISSUE TITLE
Window resizing is difficult

### ISSUE THREAD

**Issue by drdhaval2785** [JeffHoogland/moksha#96]
When I want to resize a window by dragging its sides to make it big / small, I have to be  too precise. This is very painful. Just to resize a window, I need to make slow, super slow movement of the mouse. If I slide 0.1 mm more, I miss it.
Let us have at least a 4 mm wide thing where I can resize properly.

**Comment by thewaiter** [comment]
Hello
This depends on theme you use. I made it bigger for arc green theme. The only issue could be with moksha dialogs or efl apps. Other apps created in GTK or QT have their own themes with bigger bottom right corner for mouse grabbing.

Stefan

**Comment by drdhaval2785** [comment]
Thank you for the pointer to theme. Let me give it a try.

**Comment by drdhaval2785** [comment]
I am not yet able to get this to work. Any pointer would be welcome.

**Comment by thewaiter** [comment]
Please, post a screenshot ot the screen with window you have a trouble.

**Comment by drdhaval2785** [comment]
[resizing.ogv.gz](https://github.com/JeffHoogland/moksha/files/3141153/resizing.ogv.gz)

Kindly see the screencast for the problem.

**Comment by thewaiter** [comment]
OK, I have tried it. You are right. This is GTK theme issue. Try to select Adwaita GTK theme in Applications theme settings.
https://i.imgur.com/wEBwqaI.jpg

**Comment by drdhaval2785** [comment]
Thanks.
It resolves the issue.
One has to uncheck Match Moksha theme if possible box.
